version: '3'
services:

  #PHP Service
  app:
    build:
      args:
        COMPOSER_VERSION: $${COMPOSER_VERSION?}
        XDEBUG_PORT: 9003 # default port
        XDEBUG_MODE: "off" # sets debug enabled / set off to disable
        XDEBUG_IDEKEY: idekey # sets IDE key. For phpstorm use PHPSTORM
        XDEBUG_CLIENT_HOST: host.docker.internal
      context: .
      dockerfile: Docker/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: $${PHP_IDE_CONFIG?}
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_MODE: debug

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on: 
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

#Docker Networks
networks:
  default:
    external:
      name: localnetwork